// @generated by protoc-gen-connect-es v1.7.0
// @generated from file kleron/v1/auth.proto (package kleron.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ExchangeCodeRequest, ExchangeCodeResponse, GetAuthURLRequest, GetAuthURLResponse, GetMeRequest, GetMeResponse, LogoutRequest, LogoutResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service kleron.v1.AuthService
 */
export declare const AuthService: {
  readonly typeName: "kleron.v1.AuthService",
  readonly methods: {
    /**
     * @generated from rpc kleron.v1.AuthService.GetAuthURL
     */
    readonly getAuthURL: {
      readonly name: "GetAuthURL",
      readonly I: typeof GetAuthURLRequest,
      readonly O: typeof GetAuthURLResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.AuthService.ExchangeCode
     */
    readonly exchangeCode: {
      readonly name: "ExchangeCode",
      readonly I: typeof ExchangeCodeRequest,
      readonly O: typeof ExchangeCodeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.AuthService.GetMe
     */
    readonly getMe: {
      readonly name: "GetMe",
      readonly I: typeof GetMeRequest,
      readonly O: typeof GetMeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.AuthService.Logout
     */
    readonly logout: {
      readonly name: "Logout",
      readonly I: typeof LogoutRequest,
      readonly O: typeof LogoutResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

