// @generated by protoc-gen-es v1.10.1
// @generated from file kleron/v1/auth.proto (package kleron.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message kleron.v1.User
 */
export const User = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.User",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "avatar_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message kleron.v1.GetAuthURLRequest
 */
export const GetAuthURLRequest = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.GetAuthURLRequest",
  () => [
    { no: 1, name: "provider", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code_challenge", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message kleron.v1.GetAuthURLResponse
 */
export const GetAuthURLResponse = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.GetAuthURLResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message kleron.v1.ExchangeCodeRequest
 */
export const ExchangeCodeRequest = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.ExchangeCodeRequest",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "code_verifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message kleron.v1.ExchangeCodeResponse
 */
export const ExchangeCodeResponse = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.ExchangeCodeResponse",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "expires_in", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "user", kind: "message", T: User },
  ],
);

/**
 * @generated from message kleron.v1.GetMeRequest
 */
export const GetMeRequest = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.GetMeRequest",
  [],
);

/**
 * @generated from message kleron.v1.GetMeResponse
 */
export const GetMeResponse = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.GetMeResponse",
  () => [
    { no: 1, name: "user", kind: "message", T: User },
  ],
);

/**
 * @generated from message kleron.v1.LogoutRequest
 */
export const LogoutRequest = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.LogoutRequest",
  [],
);

/**
 * @generated from message kleron.v1.LogoutResponse
 */
export const LogoutResponse = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.LogoutResponse",
  [],
);

