// @generated by protoc-gen-es v1.10.1
// @generated from file kleron/v1/auth.proto (package kleron.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message kleron.v1.User
 */
export declare class User extends Message<User> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string avatar_url = 4;
   */
  avatarUrl: string;

  constructor(data?: PartialMessage<User>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.User";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User;

  static equals(a: User | PlainMessage<User> | undefined, b: User | PlainMessage<User> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.GetAuthURLRequest
 */
export declare class GetAuthURLRequest extends Message<GetAuthURLRequest> {
  /**
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * @generated from field: string code_challenge = 2;
   */
  codeChallenge: string;

  /**
   * @generated from field: string state = 3;
   */
  state: string;

  constructor(data?: PartialMessage<GetAuthURLRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.GetAuthURLRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAuthURLRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAuthURLRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAuthURLRequest;

  static equals(a: GetAuthURLRequest | PlainMessage<GetAuthURLRequest> | undefined, b: GetAuthURLRequest | PlainMessage<GetAuthURLRequest> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.GetAuthURLResponse
 */
export declare class GetAuthURLResponse extends Message<GetAuthURLResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetAuthURLResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.GetAuthURLResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAuthURLResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAuthURLResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAuthURLResponse;

  static equals(a: GetAuthURLResponse | PlainMessage<GetAuthURLResponse> | undefined, b: GetAuthURLResponse | PlainMessage<GetAuthURLResponse> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.ExchangeCodeRequest
 */
export declare class ExchangeCodeRequest extends Message<ExchangeCodeRequest> {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string state = 2;
   */
  state: string;

  /**
   * @generated from field: string code_verifier = 3;
   */
  codeVerifier: string;

  constructor(data?: PartialMessage<ExchangeCodeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.ExchangeCodeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExchangeCodeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExchangeCodeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExchangeCodeRequest;

  static equals(a: ExchangeCodeRequest | PlainMessage<ExchangeCodeRequest> | undefined, b: ExchangeCodeRequest | PlainMessage<ExchangeCodeRequest> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.ExchangeCodeResponse
 */
export declare class ExchangeCodeResponse extends Message<ExchangeCodeResponse> {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: int64 expires_in = 2;
   */
  expiresIn: bigint;

  /**
   * @generated from field: kleron.v1.User user = 3;
   */
  user?: User;

  constructor(data?: PartialMessage<ExchangeCodeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.ExchangeCodeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExchangeCodeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExchangeCodeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExchangeCodeResponse;

  static equals(a: ExchangeCodeResponse | PlainMessage<ExchangeCodeResponse> | undefined, b: ExchangeCodeResponse | PlainMessage<ExchangeCodeResponse> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.GetMeRequest
 */
export declare class GetMeRequest extends Message<GetMeRequest> {
  constructor(data?: PartialMessage<GetMeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.GetMeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMeRequest;

  static equals(a: GetMeRequest | PlainMessage<GetMeRequest> | undefined, b: GetMeRequest | PlainMessage<GetMeRequest> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.GetMeResponse
 */
export declare class GetMeResponse extends Message<GetMeResponse> {
  /**
   * @generated from field: kleron.v1.User user = 1;
   */
  user?: User;

  constructor(data?: PartialMessage<GetMeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.GetMeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMeResponse;

  static equals(a: GetMeResponse | PlainMessage<GetMeResponse> | undefined, b: GetMeResponse | PlainMessage<GetMeResponse> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.LogoutRequest
 */
export declare class LogoutRequest extends Message<LogoutRequest> {
  constructor(data?: PartialMessage<LogoutRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.LogoutRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogoutRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogoutRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogoutRequest;

  static equals(a: LogoutRequest | PlainMessage<LogoutRequest> | undefined, b: LogoutRequest | PlainMessage<LogoutRequest> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.LogoutResponse
 */
export declare class LogoutResponse extends Message<LogoutResponse> {
  constructor(data?: PartialMessage<LogoutResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.LogoutResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogoutResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogoutResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogoutResponse;

  static equals(a: LogoutResponse | PlainMessage<LogoutResponse> | undefined, b: LogoutResponse | PlainMessage<LogoutResponse> | undefined): boolean;
}

