// @generated by protoc-gen-connect-es v1.7.0
// @generated from file kleron/v1/auth.proto (package kleron.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ExchangeCodeRequest, ExchangeCodeResponse, GetAuthURLRequest, GetAuthURLResponse, GetMeRequest, GetMeResponse, LogoutRequest, LogoutResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service kleron.v1.AuthService
 */
export const AuthService = {
  typeName: "kleron.v1.AuthService",
  methods: {
    /**
     * @generated from rpc kleron.v1.AuthService.GetAuthURL
     */
    getAuthURL: {
      name: "GetAuthURL",
      I: GetAuthURLRequest,
      O: GetAuthURLResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.AuthService.ExchangeCode
     */
    exchangeCode: {
      name: "ExchangeCode",
      I: ExchangeCodeRequest,
      O: ExchangeCodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.AuthService.GetMe
     */
    getMe: {
      name: "GetMe",
      I: GetMeRequest,
      O: GetMeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.AuthService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutResponse,
      kind: MethodKind.Unary,
    },
  }
};

