// @generated by protoc-gen-connect-es v1.7.0
// @generated from file kleron/v1/tarot.proto (package kleron.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DrawCardsRequest, DrawCardsResponse, GetCardRequest, GetCardResponse, GetReadingHistoryRequest, GetReadingHistoryResponse, SaveReadingRequest, SaveReadingResponse } from "./tarot_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service kleron.v1.TarotService
 */
export const TarotService = {
  typeName: "kleron.v1.TarotService",
  methods: {
    /**
     * @generated from rpc kleron.v1.TarotService.DrawCards
     */
    drawCards: {
      name: "DrawCards",
      I: DrawCardsRequest,
      O: DrawCardsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.TarotService.GetCard
     */
    getCard: {
      name: "GetCard",
      I: GetCardRequest,
      O: GetCardResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.TarotService.GetReadingHistory
     */
    getReadingHistory: {
      name: "GetReadingHistory",
      I: GetReadingHistoryRequest,
      O: GetReadingHistoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.TarotService.SaveReading
     */
    saveReading: {
      name: "SaveReading",
      I: SaveReadingRequest,
      O: SaveReadingResponse,
      kind: MethodKind.Unary,
    },
  }
};

