// @generated by protoc-gen-es v1.10.1
// @generated from file kleron/v1/tarot.proto (package kleron.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum kleron.v1.Suit
 */
export const Suit = /*@__PURE__*/ proto3.makeEnum(
  "kleron.v1.Suit",
  [
    {no: 0, name: "SUIT_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "SUIT_MAJOR_ARCANA", localName: "MAJOR_ARCANA"},
    {no: 2, name: "SUIT_WANDS", localName: "WANDS"},
    {no: 3, name: "SUIT_CUPS", localName: "CUPS"},
    {no: 4, name: "SUIT_SWORDS", localName: "SWORDS"},
    {no: 5, name: "SUIT_PENTACLES", localName: "PENTACLES"},
  ],
);

/**
 * @generated from message kleron.v1.Card
 */
export const Card = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.Card",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "suit", kind: "enum", T: proto3.getEnumType(Suit) },
    { no: 5, name: "image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "upright_meaning", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "reversed_meaning", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "keywords", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 9, name: "is_reversed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message kleron.v1.Reading
 */
export const Reading = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.Reading",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "cards", kind: "message", T: Card, repeated: true },
    { no: 4, name: "spread_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "question", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message kleron.v1.DrawCardsRequest
 */
export const DrawCardsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.DrawCardsRequest",
  () => [
    { no: 1, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "question", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "spread_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message kleron.v1.DrawCardsResponse
 */
export const DrawCardsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.DrawCardsResponse",
  () => [
    { no: 1, name: "cards", kind: "message", T: Card, repeated: true },
    { no: 2, name: "reading_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message kleron.v1.GetCardRequest
 */
export const GetCardRequest = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.GetCardRequest",
  () => [
    { no: 1, name: "card_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message kleron.v1.GetCardResponse
 */
export const GetCardResponse = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.GetCardResponse",
  () => [
    { no: 1, name: "card", kind: "message", T: Card },
  ],
);

/**
 * @generated from message kleron.v1.GetReadingHistoryRequest
 */
export const GetReadingHistoryRequest = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.GetReadingHistoryRequest",
  () => [
    { no: 1, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message kleron.v1.GetReadingHistoryResponse
 */
export const GetReadingHistoryResponse = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.GetReadingHistoryResponse",
  () => [
    { no: 1, name: "readings", kind: "message", T: Reading, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message kleron.v1.SaveReadingRequest
 */
export const SaveReadingRequest = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.SaveReadingRequest",
  () => [
    { no: 1, name: "card_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "reversals", kind: "scalar", T: 8 /* ScalarType.BOOL */, repeated: true },
    { no: 3, name: "question", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "spread_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message kleron.v1.SaveReadingResponse
 */
export const SaveReadingResponse = /*@__PURE__*/ proto3.makeMessageType(
  "kleron.v1.SaveReadingResponse",
  () => [
    { no: 1, name: "reading", kind: "message", T: Reading },
  ],
);

