// @generated by protoc-gen-es v1.10.1
// @generated from file kleron/v1/tarot.proto (package kleron.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum kleron.v1.Suit
 */
export declare enum Suit {
  /**
   * @generated from enum value: SUIT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SUIT_MAJOR_ARCANA = 1;
   */
  MAJOR_ARCANA = 1,

  /**
   * @generated from enum value: SUIT_WANDS = 2;
   */
  WANDS = 2,

  /**
   * @generated from enum value: SUIT_CUPS = 3;
   */
  CUPS = 3,

  /**
   * @generated from enum value: SUIT_SWORDS = 4;
   */
  SWORDS = 4,

  /**
   * @generated from enum value: SUIT_PENTACLES = 5;
   */
  PENTACLES = 5,
}

/**
 * @generated from message kleron.v1.Card
 */
export declare class Card extends Message<Card> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 number = 3;
   */
  number: number;

  /**
   * @generated from field: kleron.v1.Suit suit = 4;
   */
  suit: Suit;

  /**
   * @generated from field: string image_url = 5;
   */
  imageUrl: string;

  /**
   * @generated from field: string upright_meaning = 6;
   */
  uprightMeaning: string;

  /**
   * @generated from field: string reversed_meaning = 7;
   */
  reversedMeaning: string;

  /**
   * @generated from field: repeated string keywords = 8;
   */
  keywords: string[];

  /**
   * @generated from field: bool is_reversed = 9;
   */
  isReversed: boolean;

  /**
   * @generated from field: string description = 10;
   */
  description: string;

  constructor(data?: PartialMessage<Card>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.Card";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Card;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Card;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Card;

  static equals(a: Card | PlainMessage<Card> | undefined, b: Card | PlainMessage<Card> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.Reading
 */
export declare class Reading extends Message<Reading> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: repeated kleron.v1.Card cards = 3;
   */
  cards: Card[];

  /**
   * @generated from field: string spread_type = 4;
   */
  spreadType: string;

  /**
   * @generated from field: string question = 5;
   */
  question: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<Reading>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.Reading";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Reading;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Reading;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Reading;

  static equals(a: Reading | PlainMessage<Reading> | undefined, b: Reading | PlainMessage<Reading> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.DrawCardsRequest
 */
export declare class DrawCardsRequest extends Message<DrawCardsRequest> {
  /**
   * @generated from field: int32 count = 1;
   */
  count: number;

  /**
   * @generated from field: string question = 2;
   */
  question: string;

  /**
   * @generated from field: string spread_type = 3;
   */
  spreadType: string;

  constructor(data?: PartialMessage<DrawCardsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.DrawCardsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DrawCardsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DrawCardsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DrawCardsRequest;

  static equals(a: DrawCardsRequest | PlainMessage<DrawCardsRequest> | undefined, b: DrawCardsRequest | PlainMessage<DrawCardsRequest> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.DrawCardsResponse
 */
export declare class DrawCardsResponse extends Message<DrawCardsResponse> {
  /**
   * @generated from field: repeated kleron.v1.Card cards = 1;
   */
  cards: Card[];

  /**
   * @generated from field: string reading_id = 2;
   */
  readingId: string;

  constructor(data?: PartialMessage<DrawCardsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.DrawCardsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DrawCardsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DrawCardsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DrawCardsResponse;

  static equals(a: DrawCardsResponse | PlainMessage<DrawCardsResponse> | undefined, b: DrawCardsResponse | PlainMessage<DrawCardsResponse> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.GetCardRequest
 */
export declare class GetCardRequest extends Message<GetCardRequest> {
  /**
   * @generated from field: string card_id = 1;
   */
  cardId: string;

  constructor(data?: PartialMessage<GetCardRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.GetCardRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCardRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCardRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCardRequest;

  static equals(a: GetCardRequest | PlainMessage<GetCardRequest> | undefined, b: GetCardRequest | PlainMessage<GetCardRequest> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.GetCardResponse
 */
export declare class GetCardResponse extends Message<GetCardResponse> {
  /**
   * @generated from field: kleron.v1.Card card = 1;
   */
  card?: Card;

  constructor(data?: PartialMessage<GetCardResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.GetCardResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCardResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCardResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCardResponse;

  static equals(a: GetCardResponse | PlainMessage<GetCardResponse> | undefined, b: GetCardResponse | PlainMessage<GetCardResponse> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.GetReadingHistoryRequest
 */
export declare class GetReadingHistoryRequest extends Message<GetReadingHistoryRequest> {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  constructor(data?: PartialMessage<GetReadingHistoryRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.GetReadingHistoryRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetReadingHistoryRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetReadingHistoryRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetReadingHistoryRequest;

  static equals(a: GetReadingHistoryRequest | PlainMessage<GetReadingHistoryRequest> | undefined, b: GetReadingHistoryRequest | PlainMessage<GetReadingHistoryRequest> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.GetReadingHistoryResponse
 */
export declare class GetReadingHistoryResponse extends Message<GetReadingHistoryResponse> {
  /**
   * @generated from field: repeated kleron.v1.Reading readings = 1;
   */
  readings: Reading[];

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;

  constructor(data?: PartialMessage<GetReadingHistoryResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.GetReadingHistoryResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetReadingHistoryResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetReadingHistoryResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetReadingHistoryResponse;

  static equals(a: GetReadingHistoryResponse | PlainMessage<GetReadingHistoryResponse> | undefined, b: GetReadingHistoryResponse | PlainMessage<GetReadingHistoryResponse> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.SaveReadingRequest
 */
export declare class SaveReadingRequest extends Message<SaveReadingRequest> {
  /**
   * @generated from field: repeated string card_ids = 1;
   */
  cardIds: string[];

  /**
   * @generated from field: repeated bool reversals = 2;
   */
  reversals: boolean[];

  /**
   * @generated from field: string question = 3;
   */
  question: string;

  /**
   * @generated from field: string spread_type = 4;
   */
  spreadType: string;

  constructor(data?: PartialMessage<SaveReadingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.SaveReadingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SaveReadingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SaveReadingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SaveReadingRequest;

  static equals(a: SaveReadingRequest | PlainMessage<SaveReadingRequest> | undefined, b: SaveReadingRequest | PlainMessage<SaveReadingRequest> | undefined): boolean;
}

/**
 * @generated from message kleron.v1.SaveReadingResponse
 */
export declare class SaveReadingResponse extends Message<SaveReadingResponse> {
  /**
   * @generated from field: kleron.v1.Reading reading = 1;
   */
  reading?: Reading;

  constructor(data?: PartialMessage<SaveReadingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "kleron.v1.SaveReadingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SaveReadingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SaveReadingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SaveReadingResponse;

  static equals(a: SaveReadingResponse | PlainMessage<SaveReadingResponse> | undefined, b: SaveReadingResponse | PlainMessage<SaveReadingResponse> | undefined): boolean;
}

