// @generated by protoc-gen-connect-es v1.7.0
// @generated from file kleron/v1/tarot.proto (package kleron.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DrawCardsRequest, DrawCardsResponse, GetCardRequest, GetCardResponse, GetReadingHistoryRequest, GetReadingHistoryResponse, SaveReadingRequest, SaveReadingResponse } from "./tarot_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service kleron.v1.TarotService
 */
export declare const TarotService: {
  readonly typeName: "kleron.v1.TarotService",
  readonly methods: {
    /**
     * @generated from rpc kleron.v1.TarotService.DrawCards
     */
    readonly drawCards: {
      readonly name: "DrawCards",
      readonly I: typeof DrawCardsRequest,
      readonly O: typeof DrawCardsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.TarotService.GetCard
     */
    readonly getCard: {
      readonly name: "GetCard",
      readonly I: typeof GetCardRequest,
      readonly O: typeof GetCardResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.TarotService.GetReadingHistory
     */
    readonly getReadingHistory: {
      readonly name: "GetReadingHistory",
      readonly I: typeof GetReadingHistoryRequest,
      readonly O: typeof GetReadingHistoryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc kleron.v1.TarotService.SaveReading
     */
    readonly saveReading: {
      readonly name: "SaveReading",
      readonly I: typeof SaveReadingRequest,
      readonly O: typeof SaveReadingResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

