// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: kleron/v1/auth.proto

package kleronv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "kleron/server/pb/kleron/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "kleron.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceGetAuthURLProcedure is the fully-qualified name of the AuthService's GetAuthURL RPC.
	AuthServiceGetAuthURLProcedure = "/kleron.v1.AuthService/GetAuthURL"
	// AuthServiceExchangeCodeProcedure is the fully-qualified name of the AuthService's ExchangeCode
	// RPC.
	AuthServiceExchangeCodeProcedure = "/kleron.v1.AuthService/ExchangeCode"
	// AuthServiceGetMeProcedure is the fully-qualified name of the AuthService's GetMe RPC.
	AuthServiceGetMeProcedure = "/kleron.v1.AuthService/GetMe"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/kleron.v1.AuthService/Logout"
)

// AuthServiceClient is a client for the kleron.v1.AuthService service.
type AuthServiceClient interface {
	GetAuthURL(context.Context, *connect.Request[v1.GetAuthURLRequest]) (*connect.Response[v1.GetAuthURLResponse], error)
	ExchangeCode(context.Context, *connect.Request[v1.ExchangeCodeRequest]) (*connect.Response[v1.ExchangeCodeResponse], error)
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
}

// NewAuthServiceClient constructs a client for the kleron.v1.AuthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_kleron_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		getAuthURL: connect.NewClient[v1.GetAuthURLRequest, v1.GetAuthURLResponse](
			httpClient,
			baseURL+AuthServiceGetAuthURLProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetAuthURL")),
			connect.WithClientOptions(opts...),
		),
		exchangeCode: connect.NewClient[v1.ExchangeCodeRequest, v1.ExchangeCodeResponse](
			httpClient,
			baseURL+AuthServiceExchangeCodeProcedure,
			connect.WithSchema(authServiceMethods.ByName("ExchangeCode")),
			connect.WithClientOptions(opts...),
		),
		getMe: connect.NewClient[v1.GetMeRequest, v1.GetMeResponse](
			httpClient,
			baseURL+AuthServiceGetMeProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetMe")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.LogoutRequest, v1.LogoutResponse](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	getAuthURL   *connect.Client[v1.GetAuthURLRequest, v1.GetAuthURLResponse]
	exchangeCode *connect.Client[v1.ExchangeCodeRequest, v1.ExchangeCodeResponse]
	getMe        *connect.Client[v1.GetMeRequest, v1.GetMeResponse]
	logout       *connect.Client[v1.LogoutRequest, v1.LogoutResponse]
}

// GetAuthURL calls kleron.v1.AuthService.GetAuthURL.
func (c *authServiceClient) GetAuthURL(ctx context.Context, req *connect.Request[v1.GetAuthURLRequest]) (*connect.Response[v1.GetAuthURLResponse], error) {
	return c.getAuthURL.CallUnary(ctx, req)
}

// ExchangeCode calls kleron.v1.AuthService.ExchangeCode.
func (c *authServiceClient) ExchangeCode(ctx context.Context, req *connect.Request[v1.ExchangeCodeRequest]) (*connect.Response[v1.ExchangeCodeResponse], error) {
	return c.exchangeCode.CallUnary(ctx, req)
}

// GetMe calls kleron.v1.AuthService.GetMe.
func (c *authServiceClient) GetMe(ctx context.Context, req *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return c.getMe.CallUnary(ctx, req)
}

// Logout calls kleron.v1.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the kleron.v1.AuthService service.
type AuthServiceHandler interface {
	GetAuthURL(context.Context, *connect.Request[v1.GetAuthURLRequest]) (*connect.Response[v1.GetAuthURLResponse], error)
	ExchangeCode(context.Context, *connect.Request[v1.ExchangeCodeRequest]) (*connect.Response[v1.ExchangeCodeResponse], error)
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_kleron_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceGetAuthURLHandler := connect.NewUnaryHandler(
		AuthServiceGetAuthURLProcedure,
		svc.GetAuthURL,
		connect.WithSchema(authServiceMethods.ByName("GetAuthURL")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceExchangeCodeHandler := connect.NewUnaryHandler(
		AuthServiceExchangeCodeProcedure,
		svc.ExchangeCode,
		connect.WithSchema(authServiceMethods.ByName("ExchangeCode")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetMeHandler := connect.NewUnaryHandler(
		AuthServiceGetMeProcedure,
		svc.GetMe,
		connect.WithSchema(authServiceMethods.ByName("GetMe")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	return "/kleron.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceGetAuthURLProcedure:
			authServiceGetAuthURLHandler.ServeHTTP(w, r)
		case AuthServiceExchangeCodeProcedure:
			authServiceExchangeCodeHandler.ServeHTTP(w, r)
		case AuthServiceGetMeProcedure:
			authServiceGetMeHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) GetAuthURL(context.Context, *connect.Request[v1.GetAuthURLRequest]) (*connect.Response[v1.GetAuthURLResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kleron.v1.AuthService.GetAuthURL is not implemented"))
}

func (UnimplementedAuthServiceHandler) ExchangeCode(context.Context, *connect.Request[v1.ExchangeCodeRequest]) (*connect.Response[v1.ExchangeCodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kleron.v1.AuthService.ExchangeCode is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kleron.v1.AuthService.GetMe is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kleron.v1.AuthService.Logout is not implemented"))
}
