// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: kleron/v1/tarot.proto

package kleronv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "kleron/server/pb/kleron/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TarotServiceName is the fully-qualified name of the TarotService service.
	TarotServiceName = "kleron.v1.TarotService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TarotServiceDrawCardsProcedure is the fully-qualified name of the TarotService's DrawCards RPC.
	TarotServiceDrawCardsProcedure = "/kleron.v1.TarotService/DrawCards"
	// TarotServiceGetCardProcedure is the fully-qualified name of the TarotService's GetCard RPC.
	TarotServiceGetCardProcedure = "/kleron.v1.TarotService/GetCard"
	// TarotServiceGetReadingHistoryProcedure is the fully-qualified name of the TarotService's
	// GetReadingHistory RPC.
	TarotServiceGetReadingHistoryProcedure = "/kleron.v1.TarotService/GetReadingHistory"
	// TarotServiceSaveReadingProcedure is the fully-qualified name of the TarotService's SaveReading
	// RPC.
	TarotServiceSaveReadingProcedure = "/kleron.v1.TarotService/SaveReading"
)

// TarotServiceClient is a client for the kleron.v1.TarotService service.
type TarotServiceClient interface {
	DrawCards(context.Context, *connect.Request[v1.DrawCardsRequest]) (*connect.Response[v1.DrawCardsResponse], error)
	GetCard(context.Context, *connect.Request[v1.GetCardRequest]) (*connect.Response[v1.GetCardResponse], error)
	GetReadingHistory(context.Context, *connect.Request[v1.GetReadingHistoryRequest]) (*connect.Response[v1.GetReadingHistoryResponse], error)
	SaveReading(context.Context, *connect.Request[v1.SaveReadingRequest]) (*connect.Response[v1.SaveReadingResponse], error)
}

// NewTarotServiceClient constructs a client for the kleron.v1.TarotService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTarotServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TarotServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tarotServiceMethods := v1.File_kleron_v1_tarot_proto.Services().ByName("TarotService").Methods()
	return &tarotServiceClient{
		drawCards: connect.NewClient[v1.DrawCardsRequest, v1.DrawCardsResponse](
			httpClient,
			baseURL+TarotServiceDrawCardsProcedure,
			connect.WithSchema(tarotServiceMethods.ByName("DrawCards")),
			connect.WithClientOptions(opts...),
		),
		getCard: connect.NewClient[v1.GetCardRequest, v1.GetCardResponse](
			httpClient,
			baseURL+TarotServiceGetCardProcedure,
			connect.WithSchema(tarotServiceMethods.ByName("GetCard")),
			connect.WithClientOptions(opts...),
		),
		getReadingHistory: connect.NewClient[v1.GetReadingHistoryRequest, v1.GetReadingHistoryResponse](
			httpClient,
			baseURL+TarotServiceGetReadingHistoryProcedure,
			connect.WithSchema(tarotServiceMethods.ByName("GetReadingHistory")),
			connect.WithClientOptions(opts...),
		),
		saveReading: connect.NewClient[v1.SaveReadingRequest, v1.SaveReadingResponse](
			httpClient,
			baseURL+TarotServiceSaveReadingProcedure,
			connect.WithSchema(tarotServiceMethods.ByName("SaveReading")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tarotServiceClient implements TarotServiceClient.
type tarotServiceClient struct {
	drawCards         *connect.Client[v1.DrawCardsRequest, v1.DrawCardsResponse]
	getCard           *connect.Client[v1.GetCardRequest, v1.GetCardResponse]
	getReadingHistory *connect.Client[v1.GetReadingHistoryRequest, v1.GetReadingHistoryResponse]
	saveReading       *connect.Client[v1.SaveReadingRequest, v1.SaveReadingResponse]
}

// DrawCards calls kleron.v1.TarotService.DrawCards.
func (c *tarotServiceClient) DrawCards(ctx context.Context, req *connect.Request[v1.DrawCardsRequest]) (*connect.Response[v1.DrawCardsResponse], error) {
	return c.drawCards.CallUnary(ctx, req)
}

// GetCard calls kleron.v1.TarotService.GetCard.
func (c *tarotServiceClient) GetCard(ctx context.Context, req *connect.Request[v1.GetCardRequest]) (*connect.Response[v1.GetCardResponse], error) {
	return c.getCard.CallUnary(ctx, req)
}

// GetReadingHistory calls kleron.v1.TarotService.GetReadingHistory.
func (c *tarotServiceClient) GetReadingHistory(ctx context.Context, req *connect.Request[v1.GetReadingHistoryRequest]) (*connect.Response[v1.GetReadingHistoryResponse], error) {
	return c.getReadingHistory.CallUnary(ctx, req)
}

// SaveReading calls kleron.v1.TarotService.SaveReading.
func (c *tarotServiceClient) SaveReading(ctx context.Context, req *connect.Request[v1.SaveReadingRequest]) (*connect.Response[v1.SaveReadingResponse], error) {
	return c.saveReading.CallUnary(ctx, req)
}

// TarotServiceHandler is an implementation of the kleron.v1.TarotService service.
type TarotServiceHandler interface {
	DrawCards(context.Context, *connect.Request[v1.DrawCardsRequest]) (*connect.Response[v1.DrawCardsResponse], error)
	GetCard(context.Context, *connect.Request[v1.GetCardRequest]) (*connect.Response[v1.GetCardResponse], error)
	GetReadingHistory(context.Context, *connect.Request[v1.GetReadingHistoryRequest]) (*connect.Response[v1.GetReadingHistoryResponse], error)
	SaveReading(context.Context, *connect.Request[v1.SaveReadingRequest]) (*connect.Response[v1.SaveReadingResponse], error)
}

// NewTarotServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTarotServiceHandler(svc TarotServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tarotServiceMethods := v1.File_kleron_v1_tarot_proto.Services().ByName("TarotService").Methods()
	tarotServiceDrawCardsHandler := connect.NewUnaryHandler(
		TarotServiceDrawCardsProcedure,
		svc.DrawCards,
		connect.WithSchema(tarotServiceMethods.ByName("DrawCards")),
		connect.WithHandlerOptions(opts...),
	)
	tarotServiceGetCardHandler := connect.NewUnaryHandler(
		TarotServiceGetCardProcedure,
		svc.GetCard,
		connect.WithSchema(tarotServiceMethods.ByName("GetCard")),
		connect.WithHandlerOptions(opts...),
	)
	tarotServiceGetReadingHistoryHandler := connect.NewUnaryHandler(
		TarotServiceGetReadingHistoryProcedure,
		svc.GetReadingHistory,
		connect.WithSchema(tarotServiceMethods.ByName("GetReadingHistory")),
		connect.WithHandlerOptions(opts...),
	)
	tarotServiceSaveReadingHandler := connect.NewUnaryHandler(
		TarotServiceSaveReadingProcedure,
		svc.SaveReading,
		connect.WithSchema(tarotServiceMethods.ByName("SaveReading")),
		connect.WithHandlerOptions(opts...),
	)
	return "/kleron.v1.TarotService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TarotServiceDrawCardsProcedure:
			tarotServiceDrawCardsHandler.ServeHTTP(w, r)
		case TarotServiceGetCardProcedure:
			tarotServiceGetCardHandler.ServeHTTP(w, r)
		case TarotServiceGetReadingHistoryProcedure:
			tarotServiceGetReadingHistoryHandler.ServeHTTP(w, r)
		case TarotServiceSaveReadingProcedure:
			tarotServiceSaveReadingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTarotServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTarotServiceHandler struct{}

func (UnimplementedTarotServiceHandler) DrawCards(context.Context, *connect.Request[v1.DrawCardsRequest]) (*connect.Response[v1.DrawCardsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kleron.v1.TarotService.DrawCards is not implemented"))
}

func (UnimplementedTarotServiceHandler) GetCard(context.Context, *connect.Request[v1.GetCardRequest]) (*connect.Response[v1.GetCardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kleron.v1.TarotService.GetCard is not implemented"))
}

func (UnimplementedTarotServiceHandler) GetReadingHistory(context.Context, *connect.Request[v1.GetReadingHistoryRequest]) (*connect.Response[v1.GetReadingHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kleron.v1.TarotService.GetReadingHistory is not implemented"))
}

func (UnimplementedTarotServiceHandler) SaveReading(context.Context, *connect.Request[v1.SaveReadingRequest]) (*connect.Response[v1.SaveReadingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kleron.v1.TarotService.SaveReading is not implemented"))
}
