// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: kleron/v1/tarot.proto

package kleronv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suit int32

const (
	Suit_SUIT_UNSPECIFIED  Suit = 0
	Suit_SUIT_MAJOR_ARCANA Suit = 1
	Suit_SUIT_WANDS        Suit = 2
	Suit_SUIT_CUPS         Suit = 3
	Suit_SUIT_SWORDS       Suit = 4
	Suit_SUIT_PENTACLES    Suit = 5
)

// Enum value maps for Suit.
var (
	Suit_name = map[int32]string{
		0: "SUIT_UNSPECIFIED",
		1: "SUIT_MAJOR_ARCANA",
		2: "SUIT_WANDS",
		3: "SUIT_CUPS",
		4: "SUIT_SWORDS",
		5: "SUIT_PENTACLES",
	}
	Suit_value = map[string]int32{
		"SUIT_UNSPECIFIED":  0,
		"SUIT_MAJOR_ARCANA": 1,
		"SUIT_WANDS":        2,
		"SUIT_CUPS":         3,
		"SUIT_SWORDS":       4,
		"SUIT_PENTACLES":    5,
	}
)

func (x Suit) Enum() *Suit {
	p := new(Suit)
	*p = x
	return p
}

func (x Suit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suit) Descriptor() protoreflect.EnumDescriptor {
	return file_kleron_v1_tarot_proto_enumTypes[0].Descriptor()
}

func (Suit) Type() protoreflect.EnumType {
	return &file_kleron_v1_tarot_proto_enumTypes[0]
}

func (x Suit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suit.Descriptor instead.
func (Suit) EnumDescriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{0}
}

type Card struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Number          int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Suit            Suit                   `protobuf:"varint,4,opt,name=suit,proto3,enum=kleron.v1.Suit" json:"suit,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	UprightMeaning  string                 `protobuf:"bytes,6,opt,name=upright_meaning,json=uprightMeaning,proto3" json:"upright_meaning,omitempty"`
	ReversedMeaning string                 `protobuf:"bytes,7,opt,name=reversed_meaning,json=reversedMeaning,proto3" json:"reversed_meaning,omitempty"`
	Keywords        []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	IsReversed      bool                   `protobuf:"varint,9,opt,name=is_reversed,json=isReversed,proto3" json:"is_reversed,omitempty"`
	Description     string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Card) GetSuit() Suit {
	if x != nil {
		return x.Suit
	}
	return Suit_SUIT_UNSPECIFIED
}

func (x *Card) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Card) GetUprightMeaning() string {
	if x != nil {
		return x.UprightMeaning
	}
	return ""
}

func (x *Card) GetReversedMeaning() string {
	if x != nil {
		return x.ReversedMeaning
	}
	return ""
}

func (x *Card) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Card) GetIsReversed() bool {
	if x != nil {
		return x.IsReversed
	}
	return false
}

func (x *Card) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Reading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	SpreadType    string                 `protobuf:"bytes,4,opt,name=spread_type,json=spreadType,proto3" json:"spread_type,omitempty"`
	Question      string                 `protobuf:"bytes,5,opt,name=question,proto3" json:"question,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reading) Reset() {
	*x = Reading{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reading) ProtoMessage() {}

func (x *Reading) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reading.ProtoReflect.Descriptor instead.
func (*Reading) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{1}
}

func (x *Reading) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reading) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reading) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Reading) GetSpreadType() string {
	if x != nil {
		return x.SpreadType
	}
	return ""
}

func (x *Reading) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Reading) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DrawCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	SpreadType    string                 `protobuf:"bytes,3,opt,name=spread_type,json=spreadType,proto3" json:"spread_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawCardsRequest) Reset() {
	*x = DrawCardsRequest{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawCardsRequest) ProtoMessage() {}

func (x *DrawCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawCardsRequest.ProtoReflect.Descriptor instead.
func (*DrawCardsRequest) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{2}
}

func (x *DrawCardsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DrawCardsRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *DrawCardsRequest) GetSpreadType() string {
	if x != nil {
		return x.SpreadType
	}
	return ""
}

type DrawCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	ReadingId     string                 `protobuf:"bytes,2,opt,name=reading_id,json=readingId,proto3" json:"reading_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawCardsResponse) Reset() {
	*x = DrawCardsResponse{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawCardsResponse) ProtoMessage() {}

func (x *DrawCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawCardsResponse.ProtoReflect.Descriptor instead.
func (*DrawCardsResponse) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{3}
}

func (x *DrawCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *DrawCardsResponse) GetReadingId() string {
	if x != nil {
		return x.ReadingId
	}
	return ""
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{4}
}

func (x *GetCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{5}
}

func (x *GetCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetReadingHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingHistoryRequest) Reset() {
	*x = GetReadingHistoryRequest{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingHistoryRequest) ProtoMessage() {}

func (x *GetReadingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetReadingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{6}
}

func (x *GetReadingHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetReadingHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetReadingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*Reading             `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingHistoryResponse) Reset() {
	*x = GetReadingHistoryResponse{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingHistoryResponse) ProtoMessage() {}

func (x *GetReadingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetReadingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{7}
}

func (x *GetReadingHistoryResponse) GetReadings() []*Reading {
	if x != nil {
		return x.Readings
	}
	return nil
}

func (x *GetReadingHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SaveReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardIds       []string               `protobuf:"bytes,1,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	Reversals     []bool                 `protobuf:"varint,2,rep,packed,name=reversals,proto3" json:"reversals,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	SpreadType    string                 `protobuf:"bytes,4,opt,name=spread_type,json=spreadType,proto3" json:"spread_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveReadingRequest) Reset() {
	*x = SaveReadingRequest{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveReadingRequest) ProtoMessage() {}

func (x *SaveReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveReadingRequest.ProtoReflect.Descriptor instead.
func (*SaveReadingRequest) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{8}
}

func (x *SaveReadingRequest) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

func (x *SaveReadingRequest) GetReversals() []bool {
	if x != nil {
		return x.Reversals
	}
	return nil
}

func (x *SaveReadingRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *SaveReadingRequest) GetSpreadType() string {
	if x != nil {
		return x.SpreadType
	}
	return ""
}

type SaveReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reading       *Reading               `protobuf:"bytes,1,opt,name=reading,proto3" json:"reading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveReadingResponse) Reset() {
	*x = SaveReadingResponse{}
	mi := &file_kleron_v1_tarot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveReadingResponse) ProtoMessage() {}

func (x *SaveReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kleron_v1_tarot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveReadingResponse.ProtoReflect.Descriptor instead.
func (*SaveReadingResponse) Descriptor() ([]byte, []int) {
	return file_kleron_v1_tarot_proto_rawDescGZIP(), []int{9}
}

func (x *SaveReadingResponse) GetReading() *Reading {
	if x != nil {
		return x.Reading
	}
	return nil
}

var File_kleron_v1_tarot_proto protoreflect.FileDescriptor

const file_kleron_v1_tarot_proto_rawDesc = "" +
	"\n" +
	"\x15kleron/v1/tarot.proto\x12\tkleron.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12#\n" +
	"\x04suit\x18\x04 \x01(\x0e2\x0f.kleron.v1.SuitR\x04suit\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12'\n" +
	"\x0fupright_meaning\x18\x06 \x01(\tR\x0euprightMeaning\x12)\n" +
	"\x10reversed_meaning\x18\a \x01(\tR\x0freversedMeaning\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\x12\x1f\n" +
	"\vis_reversed\x18\t \x01(\bR\n" +
	"isReversed\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"\xd1\x01\n" +
	"\aReading\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x05cards\x18\x03 \x03(\v2\x0f.kleron.v1.CardR\x05cards\x12\x1f\n" +
	"\vspread_type\x18\x04 \x01(\tR\n" +
	"spreadType\x12\x1a\n" +
	"\bquestion\x18\x05 \x01(\tR\bquestion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\x10DrawCardsRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x1f\n" +
	"\vspread_type\x18\x03 \x01(\tR\n" +
	"spreadType\"Y\n" +
	"\x11DrawCardsResponse\x12%\n" +
	"\x05cards\x18\x01 \x03(\v2\x0f.kleron.v1.CardR\x05cards\x12\x1d\n" +
	"\n" +
	"reading_id\x18\x02 \x01(\tR\treadingId\")\n" +
	"\x0eGetCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"6\n" +
	"\x0fGetCardResponse\x12#\n" +
	"\x04card\x18\x01 \x01(\v2\x0f.kleron.v1.CardR\x04card\"K\n" +
	"\x18GetReadingHistoryRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"a\n" +
	"\x19GetReadingHistoryResponse\x12.\n" +
	"\breadings\x18\x01 \x03(\v2\x12.kleron.v1.ReadingR\breadings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8a\x01\n" +
	"\x12SaveReadingRequest\x12\x19\n" +
	"\bcard_ids\x18\x01 \x03(\tR\acardIds\x12\x1c\n" +
	"\treversals\x18\x02 \x03(\bR\treversals\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x1f\n" +
	"\vspread_type\x18\x04 \x01(\tR\n" +
	"spreadType\"C\n" +
	"\x13SaveReadingResponse\x12,\n" +
	"\areading\x18\x01 \x01(\v2\x12.kleron.v1.ReadingR\areading*w\n" +
	"\x04Suit\x12\x14\n" +
	"\x10SUIT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SUIT_MAJOR_ARCANA\x10\x01\x12\x0e\n" +
	"\n" +
	"SUIT_WANDS\x10\x02\x12\r\n" +
	"\tSUIT_CUPS\x10\x03\x12\x0f\n" +
	"\vSUIT_SWORDS\x10\x04\x12\x12\n" +
	"\x0eSUIT_PENTACLES\x10\x052\xc6\x02\n" +
	"\fTarotService\x12F\n" +
	"\tDrawCards\x12\x1b.kleron.v1.DrawCardsRequest\x1a\x1c.kleron.v1.DrawCardsResponse\x12@\n" +
	"\aGetCard\x12\x19.kleron.v1.GetCardRequest\x1a\x1a.kleron.v1.GetCardResponse\x12^\n" +
	"\x11GetReadingHistory\x12#.kleron.v1.GetReadingHistoryRequest\x1a$.kleron.v1.GetReadingHistoryResponse\x12L\n" +
	"\vSaveReading\x12\x1d.kleron.v1.SaveReadingRequest\x1a\x1e.kleron.v1.SaveReadingResponseB%Z#kleron/server/pb/kleron/v1;kleronv1b\x06proto3"

var (
	file_kleron_v1_tarot_proto_rawDescOnce sync.Once
	file_kleron_v1_tarot_proto_rawDescData []byte
)

func file_kleron_v1_tarot_proto_rawDescGZIP() []byte {
	file_kleron_v1_tarot_proto_rawDescOnce.Do(func() {
		file_kleron_v1_tarot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kleron_v1_tarot_proto_rawDesc), len(file_kleron_v1_tarot_proto_rawDesc)))
	})
	return file_kleron_v1_tarot_proto_rawDescData
}

var file_kleron_v1_tarot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kleron_v1_tarot_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kleron_v1_tarot_proto_goTypes = []any{
	(Suit)(0),                         // 0: kleron.v1.Suit
	(*Card)(nil),                      // 1: kleron.v1.Card
	(*Reading)(nil),                   // 2: kleron.v1.Reading
	(*DrawCardsRequest)(nil),          // 3: kleron.v1.DrawCardsRequest
	(*DrawCardsResponse)(nil),         // 4: kleron.v1.DrawCardsResponse
	(*GetCardRequest)(nil),            // 5: kleron.v1.GetCardRequest
	(*GetCardResponse)(nil),           // 6: kleron.v1.GetCardResponse
	(*GetReadingHistoryRequest)(nil),  // 7: kleron.v1.GetReadingHistoryRequest
	(*GetReadingHistoryResponse)(nil), // 8: kleron.v1.GetReadingHistoryResponse
	(*SaveReadingRequest)(nil),        // 9: kleron.v1.SaveReadingRequest
	(*SaveReadingResponse)(nil),       // 10: kleron.v1.SaveReadingResponse
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_kleron_v1_tarot_proto_depIdxs = []int32{
	0,  // 0: kleron.v1.Card.suit:type_name -> kleron.v1.Suit
	1,  // 1: kleron.v1.Reading.cards:type_name -> kleron.v1.Card
	11, // 2: kleron.v1.Reading.created_at:type_name -> google.protobuf.Timestamp
	1,  // 3: kleron.v1.DrawCardsResponse.cards:type_name -> kleron.v1.Card
	1,  // 4: kleron.v1.GetCardResponse.card:type_name -> kleron.v1.Card
	2,  // 5: kleron.v1.GetReadingHistoryResponse.readings:type_name -> kleron.v1.Reading
	2,  // 6: kleron.v1.SaveReadingResponse.reading:type_name -> kleron.v1.Reading
	3,  // 7: kleron.v1.TarotService.DrawCards:input_type -> kleron.v1.DrawCardsRequest
	5,  // 8: kleron.v1.TarotService.GetCard:input_type -> kleron.v1.GetCardRequest
	7,  // 9: kleron.v1.TarotService.GetReadingHistory:input_type -> kleron.v1.GetReadingHistoryRequest
	9,  // 10: kleron.v1.TarotService.SaveReading:input_type -> kleron.v1.SaveReadingRequest
	4,  // 11: kleron.v1.TarotService.DrawCards:output_type -> kleron.v1.DrawCardsResponse
	6,  // 12: kleron.v1.TarotService.GetCard:output_type -> kleron.v1.GetCardResponse
	8,  // 13: kleron.v1.TarotService.GetReadingHistory:output_type -> kleron.v1.GetReadingHistoryResponse
	10, // 14: kleron.v1.TarotService.SaveReading:output_type -> kleron.v1.SaveReadingResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_kleron_v1_tarot_proto_init() }
func file_kleron_v1_tarot_proto_init() {
	if File_kleron_v1_tarot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kleron_v1_tarot_proto_rawDesc), len(file_kleron_v1_tarot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kleron_v1_tarot_proto_goTypes,
		DependencyIndexes: file_kleron_v1_tarot_proto_depIdxs,
		EnumInfos:         file_kleron_v1_tarot_proto_enumTypes,
		MessageInfos:      file_kleron_v1_tarot_proto_msgTypes,
	}.Build()
	File_kleron_v1_tarot_proto = out.File
	file_kleron_v1_tarot_proto_goTypes = nil
	file_kleron_v1_tarot_proto_depIdxs = nil
}
